# Generated by Django 5.0.6 on 2024-06-28 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApi', '0002_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
